import Essentials from './../../components/essentials.jsx';
import ImageHeader from './../../components/image-header.jsx';
import Paragraph from './../../components/paragraph.jsx';
import SectionHeader from '../../components/park-review-header.jsx'
import wrigleyFieldImg from './../../images/Wrigley Field.jpg';

export default function App(){
	return (
		<Essentials>
		<div className='w-10/12 bg-zinc-50 block rounded-lg p-4'>
		<ImageHeader imageLink={wrigleyFieldImg} headerText={'Wrigley Field Review'} />
		<SectionHeader>Intro</SectionHeader>
		<Paragraph>This was my second ever park, and it was a pretty great second park to go to. However, I am writing this review almost 9 years after the game, so I won't have as many details, compared to more recent reviews. But nonetheless, I hope this review will be an interesting read.</Paragraph>
		<SectionHeader>Exterior</SectionHeader>
		<Paragraph>I believe there were 4 gates when I went to the game; one at home plate, one each of the left and right field corners, and one in center field into the bleachers. The bleachers were completely redone the offseason after I visited, and I didn't sit out there, so I do not remember what it was like. Since I was there in 2014, there was a large banner on the front of the home plate entrance, that had the years 1914 and 2014, along with an "IT'S THE PARTY OF THE CENTURY" banner. There is also the famous Wrigley Field marquee, that has been there for decades.</Paragraph>
		<SectionHeader>Concourses</SectionHeader>
		<Paragraph>Entering the park, you immediately felt taken back in time. The concourses were understandably much smaller than T-Mobile Park, as that was the only stadium I had been to before at that point, but even looking back, it was smaller relative to most parks you'd find today. Also different from most other parks, the concourse is below the main deck, and so you have to take tunnels up to the main concourse. In Seattle, all the rows are in front of the concourse, and you walk down to your seat no matter where you are on the first level. So that was a big change here. There were also different naming schemes here. I have a photo of the sign above one of the tunnels, that says "Field Box Aisles 106-109" and "Terrace Box Aisles 205-208". If I remember correctly, we sat in a field box seat. I also remember that the concourse was extremely flat, in that if someone stood up several rows in front of you, it would block your view, whereas in Seattle, the slope was steep enough that someone ten rows in front of you wouldn't matter at all.</Paragraph>
		<Paragraph>Wrigley Field does have an upper deck, though it's understandably entirely in foul territory. The only jewel box era parks that lasted a long time and had an upper deck beyond the outfield were Tiger Stadium and Comiskey Park. I don't think I was able to get up to the upper deck, either because I wasn't interested or I simply wasn't allowed to by the staff. I know that going to the bleachers actually required you to go out of the park, which was <i>very</i> interesting. To date, it's the only park I've been to that has a completely disconnected outfield seats, and will probably be the only one ever like that. I think this was also changed in recent years as they've made several improvements to the park.</Paragraph>
		<SectionHeader>Field</SectionHeader>
		<Paragraph>The dimensions at Wrigley had some changes early in it's history, but have largely remained the same for several decades. It's actually harder to hit the ball out down the lines than it is into the power alleys, as there are these little divots in the wall that angle back slightly. The distance to the lines are 353 and 355 feet for the left and right field poles respectively, which I believe are the longest distances to the poles in baseball. In 2014 the bullpens resided in the absolutely tiny amount of foul territory that exists, before the Cubs moved the bullpens below the bleachers for the 2017 season, reducing the foul ground even more. There is also the famous ivy, which was in full bloom. In the early months of the season, there are no leaves on the ivy yet, and they are usually fully grown by around June.</Paragraph>
		<SectionHeader>Game Experience</SectionHeader>
		<Paragraph>The game experience was pretty great! Wrigley has the organ, which the Mariners don't have 99% of the time. The only time I remember them having an organ in Seattle was in a Turn Back the Clock game in 2013 (also against the Cubs as it happens), when they were throwing it back to 1906, and it was an extremely fake-sounding organ to be honest. But you could tell this organ in Wrigley was the real deal. It was playing various tunes before the game as background music. It was actually a little cloudy before the game started, to the point where the tarp was out. When it was wrapped up, the crowd that had gathered to that point applauded. Another note about Wrigley at this time, is that it had <i>no jumbotron to speak of.</i>They couldn't even show a replay review to the fans when there was a challenge during the game, because there was nothing to show it on! It was really quite a throwback in that sense. Like the rebuilt bleachers, I missed the jumbotron additions by a year, as they were added for the 2015 season. However, it really didn't detract from the experience at all. They also had someone sing along to "Take Me Out to the Ballgame" in the 7th inning stretch, which is something that Harry Caray would do long ago. There is also a manual out of town scoreboard out beyond center field, which is in the banner picture. I will swap out that banner picture if I can find a picture of the field itself, but I didn't have a great smartphone camera at the time, so I didn't take too many photos.</Paragraph>
		<SectionHeader>Conclusion</SectionHeader>
		<Paragraph>In general, Wrigley Field is an excellent experience and a must-visit for baseball fans. While I would love to return to all ballparks I've been to, Wrigley Field is near the top of the list, partly because I enjoyed it so much originally, partially because I really enjoyed Chicago, but also because there are just so many changes since I last went. When I went to Fenway Park in 2019, they had already done basically all of the big renovations to that point. But with Wrigley, I was going the year before a lot of them started. So I hope to return there soon, perhaps even in the next few years.</Paragraph>
		</div>
		</Essentials>
	)
}
